# Generated by Django 4.2.4 on 2023-12-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_moves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pokemonmoves',
            name='4_moves',
        ),
        migrations.AddConstraint(
            model_name='pokemonmoves',
            constraint=models.UniqueConstraint(fields=('pokemon', 'move_number', 'user'), name='4_moves', violation_error_message='There are already 4 moves assigned to this pokemon'),
        ),
    ]
