
services:
  pokedex-db:
    image: postgres:15
    restart: unless-stopped
    user: postgres
    env_file:
      envs/.postgres
    volumes:
      - pokedex-db-volume:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - '5432:5432'
      - '6543:5432'
    healthcheck:
       test: [ 'CMD', 'pg_isready' ]
       interval: 10s
       timeout: 5s
       retries: 5

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    env_file:
      envs/.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      envs/.django
    depends_on:
      rabbit:
        condition: service_started
      pokedex-db:
        condition: service_healthy

volumes:
  pokedex-db-volume:
