# Generated by Django 4.2.1 on 2023-06-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritepokemon',
            options={'verbose_name_plural': 'FavouritePokemons'},
        ),
        migrations.CreateModel(
            name='PokemonInTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PokemonsInTeams',
            },
        ),
        migrations.AddConstraint(
            model_name='pokemoninteam',
            constraint=models.CheckConstraint(check=models.Q(('number__gt', 6)), name='check_number_in_team', violation_error_message='There are already 6 pokemons in you team'),
        ),
    ]
