# Generated by Django 4.2.1 on 2023-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritepokemon',
            name='pokemon_name',
            field=models.CharField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
