# Generated by Django 4.2.1 on 2023-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_favouritepokemon_pokemon_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='check_number_in_team',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_type_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(check=models.Q(('pokemon_number__lt', 7)), name='check_number_in_team', violation_error_message='There are already 6 pokemons in you team'),
        ),
    ]
