# Generated by Django 4.2.4 on 2024-04-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_move_pokemonmoves_userpokemonmoves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpokemonmoves',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_moves', to='pokemons.pokemon'),
        ),
    ]
