# Generated by Django 4.2.1 on 2023-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_alter_favouritepokemon_options_pokemoninteam_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pokemoninteam',
            name='check_number_in_team',
        ),
        migrations.AddConstraint(
            model_name='pokemoninteam',
            constraint=models.CheckConstraint(check=models.Q(('number__lt', 6)), name='check_number_in_team', violation_error_message='There are already 6 pokemons in you team'),
        ),
    ]
