# Generated by Django 4.2.1 on 2023-09-11 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemons', '0003_remove_team_check_number_in_team_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='check_number_in_team',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('user', 'pokemon_number')},
        ),
    ]
