# Generated by Django 4.2.1 on 2023-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_remove_pokemoninteam_check_number_in_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninteam',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
