# Generated by Django 4.2.1 on 2023-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_remove_team_check_number_in_team_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('user', 'pokemon_number'), name='check_number_in_team', violation_error_message='There are already 6 pokemons in you team'),
        ),
    ]
