# Generated by Django 4.2.1 on 2023-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_alter_team_unique_together_team_check_number_in_team'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='check_number_in_team',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('user', 'pokemon_number'), name='unique_team', violation_error_message='There are already 6 pokemons in you team'),
        ),
    ]
