# Generated by Django 4.2.1 on 2023-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0006_remove_team_check_number_in_team_team_unique_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritepokemon',
            options={'verbose_name_plural': 'Favourite Pokemons'},
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team',
        ),
        migrations.AlterField(
            model_name='team',
            name='pokemon_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('user', 'pokemon_number'), name='unique_team', violation_error_message='There are already 6 pokemons in your team'),
        ),
    ]
