# Generated by Django 4.2.1 on 2023-09-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0007_alter_favouritepokemon_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritepokemon',
            name='pokemon_id',
        ),
        migrations.RemoveField(
            model_name='favouritepokemon',
            name='pokemon_name',
        ),
        migrations.AddField(
            model_name='favouritepokemon',
            name='pokemon',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon'),
            preserve_default=False,
        ),
    ]
