# Generated by Django 4.2.4 on 2024-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0009_pokemon_pokemon_height_pokemon_pokemon_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_entry',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
