# Generated by Django 4.2.4 on 2024-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0012_move_pokemonmoves_pokemonmoves_4_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_img',
            field=models.FilePathField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_img_shiny',
            field=models.FilePathField(max_length=200, null=True),
        ),
    ]
