# Generated by Django 4.2.4 on 2024-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0013_alter_pokemon_pokemon_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pokemon_id',
            field=models.ManyToManyField(related_name='pokemon', to='pokemons.pokemon'),
        ),
    ]
