# Generated by Django 4.2.4 on 2024-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0014_alter_team_pokemon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_entry',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_type_1',
            field=models.CharField(choices=[('grass', 'GRASS'), ('fire', 'FIRE'), ('water', 'WATER'), ('bug', 'BUG'), ('normal', 'NORMAL'), ('poison', 'POISON'), ('electric', 'ELECTRIC'), ('ground', 'GROUND'), ('fighting', 'FIGHTING'), ('psychic', 'PSYCHIC'), ('rock', 'ROCK'), ('ghost', 'GHOST'), ('ice', 'ICE'), ('dragon', 'DRAGON'), ('dark', 'DARK'), ('steel', 'STEEL'), ('flying', 'FLYING'), ('', None)], max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_type_2',
            field=models.CharField(blank=True, choices=[('grass', 'GRASS'), ('fire', 'FIRE'), ('water', 'WATER'), ('bug', 'BUG'), ('normal', 'NORMAL'), ('poison', 'POISON'), ('electric', 'ELECTRIC'), ('ground', 'GROUND'), ('fighting', 'FIGHTING'), ('psychic', 'PSYCHIC'), ('rock', 'ROCK'), ('ghost', 'GHOST'), ('ice', 'ICE'), ('dragon', 'DRAGON'), ('dark', 'DARK'), ('steel', 'STEEL'), ('flying', 'FLYING'), ('', None)], default='', max_length=50),
        ),
    ]
