# Generated by Django 4.2.4 on 2024-03-06 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0015_alter_pokemon_pokemon_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='move_accuracy',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='move',
            name='move_damage_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='move_entry',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='move_power',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='move_pp',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='move_priority',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-8), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('grass', 'GRASS'), ('fire', 'FIRE'), ('water', 'WATER'), ('bug', 'BUG'), ('normal', 'NORMAL'), ('poison', 'POISON'), ('electric', 'ELECTRIC'), ('ground', 'GROUND'), ('fighting', 'FIGHTING'), ('psychic', 'PSYCHIC'), ('rock', 'ROCK'), ('ghost', 'GHOST'), ('ice', 'ICE'), ('dragon', 'DRAGON'), ('dark', 'DARK'), ('steel', 'STEEL'), ('flying', 'FLYING'), ('', None)], max_length=50),
        ),
    ]
